node_read_time.settings:
  type: config_object
  label: 'Node read time settings'
  mapping:
    words_per_minute:
      type: integer
      label: 'Words per minute'
    unit_of_time:
      type: string
      label: 'Unit of time'
