pd_back_to_top: 0
pd_sticky_sidebars: 1
pd_logo_light: themes/custom/em_magazine/branding/logo-light.svg
pd_logo_dark: themes/custom/em_magazine/branding/logo-dark.svg
pd_search_button_text: Go
pd_search_field_placeholder_text: 'Search for...'
pd_facebook: 'https://www.facebook.com/'
pd_facebook_link_title: ''
pd_twitter: 'https://twitter.com/'
pd_twitter_link_title: ''
pd_additional_css: ''
pd_custom_css_file: 0
pd_additional_head_javascript: ''
pd_additional_body_javascript: ''
_core:
  default_config_hash: w2eifOnrHTgZieQMAxMSINRxQsGP7JzsyhYgj1Qz4Hs
features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
favicon:
  use_default: 1
pd_googleplus: 'http://googleplus.com'
pd_googleplus_link_title: ''
pd_youtube: 'http://youtube.com'
pd_youtube_link_title: ''
pd_instagram: 'http://instagram.com'
pd_instagram_link_title: ''
pd_pinterest: ''
pd_pinterest_link_title: ''
pd_tumblr: ''
pd_tumblr_link_title: ''
copyright_note: fgbr
pd_copyright_note: ''
pd_google-plus: 'http://googeplus.com'
pd_google-plus_link_title: ''
pd_scroll_to_top: 1
logo:
  use_default: 1
pd_show_cart_button: 1
pd_show_search_button: 1
pd_show_hamburger_menu: 1
pd_linked-in: 'http://linkedin.com'
pd_sticky_header: 1
pd_teaser_uppercase_title: 0
pd_teaser_show_author_info: 1
pd_teaser_show_post_date: 1
pd_teaser_date_format: short
pd_mailchimp_signup_headline: 'Sign Up for Our Newsletters'
pd_mailchimp_signup_text: 'Get awesome content in your inbox every week.'
