determine_menu: true
disable_admin_page: true
append_current_page: true
current_page_as_link: false
append_member_page: true
member_page_as_link: true
remove_home: false
add_home: true
menu_breadcrumb_menus:
  main:
    enabled: 1
    taxattach: 1
    weight: -10
    langhandle: 0
  admin:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  footer:
    enabled: 1
    taxattach: 1
    weight: 0
    langhandle: 0
  tools:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
  account:
    weight: 0
    enabled: 0
    taxattach: 0
    langhandle: 0
_core:
  default_config_hash: cQ5PlGtatt2RcAsy3ZvFrnpvCRT-VdbdrFEV-XUpEAI
front_title: 1
